### ISSUE TITLE
Crear endpoint para verificar la validez de entradas

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-gopass-back#1]
Desarrollar el endpoint POST /api/verificar-entrada que permita verificar la autenticidad de una entrada a través de la API de Ticketmaster. Asegurarse de que el código QR sea enviado correctamente y que la API de Ticketmaster devuelva un resultado válido.

**Comment by Adhe-Enne** [comment]
Se envio el primer PR con implementacion de verificacion. 
https://github.com/igrowker/i003-gopass-back/pull/30
