### ISSUE TITLE
Crear sistema de auditoría para las transacciones de reventa

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-gopass-back#13]
Desarrollar un sistema de auditoría en el backend que registre todas las transacciones de reventa realizadas en la plataforma. Esto incluirá detalles como el vendedor, comprador, entrada y precio, permitiendo un historial detallado de cada reventa.

**Comment by Ezefeola** [comment]
Se podria agregar una vista para mostrara este historial de transacciones, todos los datos ya estan almacenados en reventa
