### ISSUE TITLE
Crear pruebas unitarias para el controlador de reventa

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-gopass-back#9]
Escribir pruebas unitarias para el 'ReventaController', validando que las funciones de publicación, compra y transferencia de entradas funcionen correctamente. Las pruebas deben cubrir casos exitosos y errores.

**Comment by Adhe-Enne** [comment]
No me choreen la task onegai shimasu UwU
![Image](https://github.com/user-attachments/assets/d071385e-9bd7-4b4d-a3d8-ce33241787f2)
